apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "istio-ratelimit.fullname" . }}
  labels:
    {{- include "istio-ratelimit.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "istio-ratelimit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "istio-ratelimit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/ratelimit"]
          env:
          - name: LOG_LEVEL
            value: {{ .Values.env.logLevel }}
          - name: REDIS_SOCKET_TYPE
            value: {{ .Values.env.redis.socketType }}
          - name: REDIS_URL
            value: {{ quote .Values.env.redis.url }}
          - name: USE_STATSD
            value: {{ .Values.env.useStatsd | quote }}
          - name: HOST
            value: {{ quote .Values.env.host }}
          - name: GRPC_HOST
            value: {{ quote .Values.env.grpcHost }}
          {{- if .Values.configurations }}
          - name: RUNTIME_ROOT
            value: /data
          - name: RUNTIME_SUBDIRECTORY
            value: ratelimit
          - name: RUNTIME_WATCH_ROOT
            value: {{ .Values.env.runtimeWatchRoot | quote }}
          - name: RUNTIME_IGNOREDOTFILES
            value: {{ .Values.env.runtimeIgnoreDotFiles | quote }}
          {{- end}}
          {{- range $key, $val := .Values.env.extra }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          ports:
          - containerPort: 8080
          - containerPort: 8081
          - containerPort: 6070
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configurations }}
          volumeMounts:
          - name: config-volume
            mountPath: /data/ratelimit/config
          {{- end}}
      {{- if .Values.configurations }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "istio-ratelimit.fullname" . | printf "%s-config" }}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
