apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eg.fullname" . }}-extension-server-role
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "eg.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.imesh.ai
  resources:
  - upstreamtlspolicies
  - upstreamtlspolicies/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eg.fullname" . }}-extension-server-rolebinding
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "eg.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "eg.fullname" . }}-extension-server-role'
subjects:
- kind: ServiceAccount
  name: 'envoy-gateway'
  namespace: '{{ .Release.Namespace }}'
