clusterAgent:
  replicaCount: 1

  image:
    repository: imeshai/agent
    pullPolicy: IfNotPresent
    tag: vb99235b01b78b194a880b698a379e025cbbe8d1c

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podLabels: {}

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi

  env:
    # (REQUIRED) Agent token as provided by the UI
    agentToken: "ABCDEFGHIJ123456"
    # HTTP port, used for health check endpoint
    httpPort: 8080
    # DEBUG, WARNING, or INFO
    logLevel: WARNING
    # IMESH Platform URL
    natsUrl: nats://services.imesh.ai:4222
    # Prometheus endpoint for metric collection
    # prometheusEndpoint: prometheus:9090

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

prometheus:
  enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  alertmanager:
    enabled: false

  server:
    persistentVolume:
      enabled: false