apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include ".Values.clusterAgent.name" . }}
  labels:
    {{- include ".Values.clusterAgent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include ".Values.clusterAgent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include ".Values.clusterAgent.name" . }}
  apiGroup: rbac.authorization.k8s.io
