{{- if .Values.clusterAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".Values.clusterAgent.serviceAccountName" . }}
  labels:
    {{- include ".Values.clusterAgent.labels" . | nindent 4 }}
  {{- with .Values.clusterAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
