env:
  logLevel: debug
  useStatsd: false
  runtimeWatchRoot: false
  runtimeIgnoreDotFiles: true
  host: "::"
  grpcHost: "::"
  redis:
    url: redis:6379
    socketType: tcp
  extra: {} # for redis/etc environment variables

configurations: {}

replicaCount: 1

image:
  repository: envoyproxy/ratelimit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 9d8d70a8 # 2022/08/16

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels:
  app: ratelimit

securityContext: {}
  # fsGroup: 2000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
