apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include ".Values.clusterAgent.name" . }}
  labels:
    {{- include ".Values.clusterAgent.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces", "services", "secrets"]
  verbs: ["get", "watch", "list", "update", "create", "delete"]
- apiGroups: ["gateway.networking.k8s.io"] 
  resources: ["gateways", "httproutes"]
  verbs: ["get", "watch", "list", "update", "create", "delete"]
- apiGroups: ["gateway.envoyproxy.io"] 
  resources: ["envoypatchpolicies"]
  verbs: ["get", "watch", "list", "update", "create", "delete", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses"]
  verbs: ["get", "list"]
